### ISSUE TITLE
Support for newest ue5-main

### ISSUE THREAD

**Issue by patrick-han** [lucoiso/UEFSR#6]
Hi, thank you for your work on porting this plugin to UE5! I'm trying to compile it for the latest ue5-main changes but it seems to me the engine changes have broken it again. Are you planning further support for this plugin? Thanks!

Most of the messages relate to "Use of undefined type FViewInfo", but I suspect some of the errors are red herrings due to other errors. I've tried looking through it myself but I'm unfortunately very new to the intimidating UE API.

**Comment by lucoiso** [comment]
Updated!
